### ISSUE TITLE
本地想传送大文件，修改watch之后发现还是不行

### ISSUE THREAD

**Issue by wming3** [rentiansheng/devSync#23]
1. 修改watch配置，将14m改成了1400m
2. 使用all参数传输文件  一开始提示全部成功，过了一会提示 error【上传了一个40m左右的压缩包】
3. 在服务端，收到了传输的文件，但是不能解压成功，提示文件格式失败。。【本地解压缩没有问题】
4. 服务端提示错误为gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
5. 客户端提示错误为
error:/home/map/odp_strategy/app/strategyui/script/node.zip.gz

**Comment by rentiansheng** [comment]
问题1. 修改watch配置，将14m改成了1400m
  新加maxFileSize用来闲的文件大小，默认14.
问题2，3， 4  client 用file stream 传输数据的方式, 避免数据被编码，保证二进制传输安全

问题5： 已经优化现现有整体同步代码的工作方式，避免在文件多，文件内容大的时候， 服务端出现连接关闭和不工作的清河
